### ISSUE TITLE
Support BiometricPrompt

### ISSUE THREAD

**Issue by tinsukE** [kevalpatel2106/FingerprintDialogCompat#1]
The new P Developer Preview changed the API to a more generic [BiometricPrompt](https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt).

Will the library be updated to support that?

**Comment by kevalpatel2106** [comment]
I will look into this and make further comments.

**Comment by kevalpatel2106** [comment]
@tinsukE I looked into the BiometricPrompt. I think that support library for BiometricPrompt is already available. See this [blog](https://android-developers.googleblog.com/2018/06/better-biometrics-in-android-p.html).
